name: Do Not Submit

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false
    - uses: chainguard-dev/actions/donotsubmit@142d22e4cec7c824db396585b9bc86f76f7c1732 # v1.6.35
